---
title: "R Notebook"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}
library(googlesheets4)
library(tidyverse)
library(glue)
```

```{r}
# gs4_auth(
# email = "jacciziebert@gmail.com",
# path = NULL,
# scopes = "https://www.googleapis.com/auth/spreadsheets",
# cache = gargle::gargle_oauth_cache(),
# use_oob = gargle::gargle_oob_default(),
# token = NULL
# )
```


```{r}
resume <- read_sheet("https://docs.google.com/spreadsheets/d/1Cma5QJ6BzKUj449YECrkPvoePGNqZBebLx5EHbdZ8tk/edit?usp=sharing") %>% mutate(id = 1:n())
```

```{r}
# https://livefreeordichotomize.com/2019/09/04/building_a_data_driven_cv_with_r/
pivoted_positions <- resume %>% 
  pivot_longer(
     starts_with('description'),
     names_to = 'description_num',
     values_to = 'description',
     values_drop_na = TRUE
   )

pos_w_descrip_list <- pivoted_positions %>% 
  group_by(id) %>% 
  # Wrap all descriptions into a list column
  mutate(descriptions = list(description) ) %>% 
  ungroup() %>% 
  # Only keep first row of each expanded position rows
  filter(description_num == 'description_1') %>% 
  # We don't need these columns any more
  select(-description_num, -description)
```

```{r}
# If missing start or start is same as end
# date, just use end date. otw build range
positions_w_timeline <- pos_w_descrip_list %>% 
  mutate(
    timeline = ifelse(
      is.na(start) | start == end,
      end,
      glue('{start} - {end}')
    )
  )

positions_collapsed_bullets <- positions_w_timeline %>% 
  mutate(
     description_bullets = map_chr(
       descriptions, 
       ~paste('-', ., collapse = '\n')),
  )

positions_no_na <- positions_collapsed_bullets %>% 
  mutate_all(~ifelse(is.na(.), 'N/A', .))
```
```{r}
positions_no_na %>% 
  glue_data(
   "### {title}",
   "\n\n",
   "{company}",
   "\n\n",
   "{location}",
   "\n\n",
   "{timeline}", 
   "\n\n",
   "{description_bullets}",
   "\n\n\n"
 )
```

